apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubeflow
spec:
  generators:
  - git:
      repoURL: https://github.com/kubeflow/manifests.git
      revision: HEAD
      directories:
      - path: apps/admission-webhook/upstream/*
      - path: apps/centraldashboard/upstream/*
      - path: apps/jupyter/jupyter-web-app/upstream/*
      - path: apps/jupyter/notebook-controller/upstream/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kubeflow/manifests.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc

