apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hbb33/manifests.git
    targetRevision: HEAD
    path: ../common/istio-1-9/istio-crds/base
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true