apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hbb33/manifests.git
    targetRevision: HEAD
    path: ./common/kubeflow-namespace/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true