# ./kustomization.yaml
# https://blog.marcnuri.com/prometheus-grafana-setup-minikube

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus
  namespace: prometheus

