apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../common/istio-1-9/istio-install/base
- certificate.yaml
- PeerAuthentication.yaml
patchesStrategicMerge:
# - patches/https-gateway.yaml

