apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cluster-local-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hbb33/manifests.git
    targetRevision: HEAD
    path: ./common/istio-1-9/cluster-local-gateway/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
