apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hbb33/manifests.git
    targetRevision: HEAD
    path: ./apps/jupyter/notebook-controller/upstream/overlays/kubeflow
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true