apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- common/oidc-authservice/base
patchesStrategicMerge:
- statefulset.yaml
images:
  - name: busybox
    newTag: "latest"
    newName: busybox
